name: deploy

on:
  push:
    branches:
      - "*"

jobs:
  staging:
    name: Deploy to staging
    runs-on: roderunners
    steps:
      - uses: actions/checkout@v2

      - name: env
        run: env

      - name: Install Helm
        run: curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      - name: Add repo
        run: |
          helm repo add rode https://rode.github.io/charts
          helm repo update

      - name: Helm upgrade
        run: helm upgrade --dry-run --install --namespace rode-staging rode-staging rode/rode
